techlottus/portalverse-uane

components/FooterPortalverse.tsx, forms/fixtures/openform.ts, forms/steps/step-one-openform.tsx
=> fix space aviso de privacidad

config/educacion-continua/analisis-de-datos.json, config/educacion-continua/educacion-continua.json, config/educacion-continua/estrategias-tiendas-en-linea.json, config/educacion-continua/estructura-datos.json, config/educacion-continua/higiene-seguridad-trabajo.json, config/educacion-continua/mega-tendencias-globales.json, config/header.json, config/oferta-educativa/doctorado/planeacion-liderazgo-educativo.json, config/oferta-educativa/maestria.json, config/oferta-educativa/maestria/administracion.json, config/oferta-educativa/maestria/educacion.json, config/oferta-educativa/maestria/gobierno-estrategia-publica.json, config/oferta-educativa/maestria/mercadotecnia-digital.json, config/voz-UANE.json, routes/Routes.ts
=> fix marketing coments

config/becas.json, config/educacion-continua/educacion-continua.json, config/empleabilidad.json, config/faq.json, config/footer.json, config/header.json, config/home.json, config/internacionalizacion.json, config/oferta-educativa/bachillerato/bachillerato.json, config/oferta-educativa/licenciatura.json, config/oferta-educativa/licenciatura/negocios-digitales.json, config/oferta-educativa/maestria/mercadotecnia-digital.json, config/podcast.json, config/voz-UANE.json, routes/Routes.ts, routes/actions.ts
=> fix copys part 3

components/HeaderPortalverse/HeaderPortalverse.tsx, components/Richtext/Richtext.scss, config/home.json, config/somos-uane.json
=> feat: add slides home, fix header bug

config/home.json
=> fix: redirects slide, copys slide

config/internacionalizacion.json, config/oferta-educativa/maestria/derecho.json, config/oferta-educativa/oferta-educativa.json, forms/fixtures/openform.ts, pages/oferta-educativa/[level]/[program]/index.tsx, pages/voz-uane/blog/index.tsx, pages/voz-uane/index.tsx
we need to add urgent changes to slide internacionalizacion and add banner ofertas academicas
=> feat: add urgent changes

config/internacionalizacion.json
=> fix image internacional mobile

config/internacionalizacion.json
=> feat: add image slider internacional

config/educacion-continua/educacion-continua.json, pages/educacion-continua/index.tsx
=> feat: add flag to hide programs

config/conexion-educativa.json, config/header.json, config/internacionalizacion.json, config/landing-admisiones.json, config/oferta-educativa/doctorado.json, config/oferta-educativa/doctorado/derecho.json, config/oferta-educativa/especialidad/gestion-desarrollo-recursos-humanos.json, config/oferta-educativa/licenciatura.json, config/oferta-educativa/licenciatura/administracion-liderazgo-empresarial.json, config/oferta-educativa/licenciatura/contador-publico.json, config/oferta-educativa/licenciatura/derecho.json, config/oferta-educativa/licenciatura/desarrollo-software.json, config/oferta-educativa/licenciatura/diseno-grafico.json, config/oferta-educativa/licenciatura/gestion-deportiva.json, config/oferta-educativa/licenciatura/ingenieria-industrial-sistemas.json, config/oferta-educativa/licenciatura/mecanica-procesos-inyeccion.json, config/oferta-educativa/licenciatura/negocios-internacionales.json, config/oferta-educativa/licenciatura/psicologia.json, config/oferta-educativa/maestria.json, config/oferta-educativa/maestria/docencia.json, config/oferta-educativa/maestria/efectividad-organizacional.json, config/oferta-educativa/maestria/gobierno-estrategia-publica.json, config/somos-uane.json, pages/admisiones/index.tsx, pages/nosotros/conexion-educativa.tsx, pages/nosotros/empleabilidad.tsx, pages/oferta-educativa/[level]/index.tsx
=> prueba repo

components/SliderPortalverse.tsx, forms/container/EducacionContinuaForm.tsx, utils/getTokenForms.ts
=> feat: prueba form token

components/CardProgram/CardProgram.tsx, config/footer.json, config/internacionalizacion.json, config/somos-uane.json, pages/oferta-educativa/[level]/index.tsx
conflict position links in cards
refactor component and code
=> feat: fix position link cards, fix texts product

config/oferta-educativa/licenciatura/psicologia.json
=> fix psicología program: add online

pages/admisiones/becas.tsx, pages/nosotros/index.tsx
=> add access becas

config/internacionalizacion.json
=> feat: add not found images

components/CardWebsitePortalverse.tsx, config/landing-admisiones.json, pages/admisiones/index.tsx
=> feat: fix height card admisiones

pages/voz-uane/blog/[entry]/index.tsx, pages/voz-uane/blog/index.tsx, pages/voz-uane/index.tsx
voz uane page has not isr implemented
implemented revalidate in voz uane
changed revalidate time to 60 secs
=> hotfix: added 60 sec revalidate

config/internacionalizacion.json, pages/nosotros/internacionalizacion.tsx
=> feat: link internacionalización

components/SliderPortalverseWrapper.tsx, pages/index.tsx, utils/strapi/sections/HeroSlider.ts
Create component for slider data parsing from Strapi.
=> SliderPortalverseWrapper component

components/NumbersPortalverseWrapper.tsx, pages/index.tsx, utils/strapi/sections/StatisticsCardList.ts
Create component for numbers data parsing from Strapi.
Created NumbersPortalverseWrapper component.
=> feat: create NumbersPortalverseWrapper component

config/extension-universitaria/extension-universitaria.json
we need to change the order of sections in educational extension changes
we rearranged the programs and added the section international graduates
=> feat: changes in order programs, add new section

config/empleabilidad.json, config/landing-admisiones.json
=> feat: add changes educative offer

config/extension-universitaria/certificacion-internacional-1.json, config/extension-universitaria/certificacion-internacional-2.json, config/extension-universitaria/certificacion-internacional-3.json, config/extension-universitaria/certificacion-internacional-4.json, config/extension-universitaria/certificacion-internacional-5.json, config/extension-universitaria/certificacion-internacional-a1.json, config/extension-universitaria/certificacion-internacional-a2.json, config/extension-universitaria/certificacion-internacional-b1.json, config/extension-universitaria/certificacion-internacional-b2.json, config/extension-universitaria/certificacion-internacional-c1.json, config/extension-universitaria/certificacion-internacional-c2.json, config/podcast.json
- Update courses prices and podcast
- [feat: Change prices and update podcast](https://github.com/techlottus/portalverse-uane/commit/caba8a45bca2d7b4a8344aac15b18f3c0c3a7277)
TODO
=> Change prices

config/empleabilidad.json, config/extension-universitaria/extension-universitaria.json, config/extension-universitaria/prodis-diseno-universal.json, config/extension-universitaria/prodis-estimulacion-sensorial.json, config/extension-universitaria/prodis-metodologia-investigacion-aplicada.json, config/extension-universitaria/prodis-saac.json, config/extension-universitaria/prodis-tic.json, config/voz-UANE.json, routes/Routes.ts
we need to add new programs extension universitaria pages
We add the programs on the main page and their details
=> [DEV-add-programs]

config/somos-uane.json
- Migrate images of "nosotros" page from drive to S3 bucket
- [feat: Nosotros page images migrated](https://github.com/techlottus/portalverse-uane/commit/d5bd6e1287ee4229c9e807b2a81c140a549005a2)
- Go to `/nosotros`
- See the page and compare with [UANE](https://uane.edu.mx/nosotros) website 
=> [DEV-5198] UANE "nosotros" migrate images

config/alumnos.json, config/podcast.json, config/voz-UANE.json
we need to update podcast and episode voz-uane page
we need to change a link in alumnos page
we update the new episode in voz-uane and podcast pages
we change the link of card siuane
=> feat: update podcast, change link alumnos siuane

config/internacionalizacion.json
- Migrate images of "internacionalizacion" page from drive to S3 bucket
- [feat: internacionalizacion images migrated](https://github.com/techlottus/portalverse-uane/pull/98/commits/6c7176c1dc74e11eb3409b5fc3d07316e83120a6)
- Go to `/nosotros/internacionalizacion`
- See and compare images with [UANE](https://uane.edu.mx/nosotros/internacionalizacion) website
=> [DEV-5216] Migrate "internacionalizacion" page images

config/landing-admisiones.json
- Migrate images of "admisiones" page from drive to S3 bucket
- [feat: admisiones page images migrated](https://github.com/techlottus/portalverse-uane/commit/035c4c60d5081f994820aa37bd1369b92b4cbd4a)
- Go to `/admisiones`
- See and compare images with [UANE](https://uane.edu.mx/admisiones) website
=> [DEV-5219] Migrate "admisiones" page images

pages/admisiones/index.tsx
Reverts techlottus/portalverse-uane#109
=> Revert "TEST PR"

forms/container/OpenForm.tsx, pages/index.tsx, utils/getEducativeOffer.ts, utils/saveDataForms.ts
Reverts techlottus/portalverse-uane#102
=> Revert "[DEV-5168] Open Form Fixes"

old-components/Lottie.tsx
=> feat: test commit

config/oferta-educativa/maestria/gobierno-estrategia-publica.json, config/podcast.json, config/voz-UANE.json
We need to upadate podcast and update program pdf maestría en gobierno y estrategia
We update the podcast page with the most recent on the podcast and voz-uane pages
We update the programs of maestría en gobierno y estrategia
=> feat: update 17-04-32

config/oferta-educativa/maestria/gobierno-estrategia-publica.json
we need to add the id correct pdf maestria en gobierno y estrategia
we add the id correct pdf maestria en gobierno y estrategia
=> feat: upload correct pdf

config/empleabilidad.json, forms/container/OpenForm.tsx, pages/index.tsx, utils/getEducativeOffer.ts, utils/saveDataForms.ts
Reverts techlottus/portalverse-uane#127
=> Revert "[Hotfix ] Open Form"

pages/index.tsx
=> Trigger deploy

config/oferta-educativa/maestria/gobierno-estrategia-publica.json
we had a incorrect pdf in maestría en gobierno y estrategia modality online
we update the correct pdf
=> feat: add correct pdf to program

config/oferta-educativa/maestria/gobierno-estrategia-publica.json, pages/index.tsx
=> Merge to main

config/oferta-educativa/maestria/gobierno-estrategia-publica.json, pages/index.tsx, utils/saveDataForms.ts
Bring latest changes from `develop` branch into `main`.
=> Merge develop into main

config/extension-universitaria/comunicacion-publica-gestion-reputacion.json, config/extension-universitaria/extension-universitaria.json
We need to change the order of sections and courses on extensión universitaria page 
we change the order of sections and courses
=> [DEV-update-20-04-23] Changes estension universitaria page

config/podcast.json, config/voz-UANE.json
we need to update the latest episodes of the podcast on the voz-uane and podcast pages of the site
The podcast episodes have been updated on the voz-uane and podcast pages of the site
=> feat: update podcast

components/Aspect.tsx, components/SliderPortalverseWrapper.tsx, old-components/SliderPortalverse.tsx
- Migrate the new slider component `SliderPortalverse` from [portalver](https://github.com/techlottus/portalverse) project to this project
- [feat: new Slider component added](https://github.com/techlottus/portalverse-uane/pull/126/commits/3fc7280a56934427ec4c3d706bc256f01ab47042)
- [feat: SliderPortalverse component styles fixed](https://github.com/techlottus/portalverse-uane/pull/126/commits/7e6aa6908f97ae9b10c07e55cf4cd0fd0fc562e7)
- Go to `/` 
- Compare the slider with [figma](https://www.figma.com/file/UyzEPhE59p5Y98WGbISh3i/Portalverse-1.0?node-id=6428-53805&t=G32j5hUA8MH1vgkh-0) file and [UANE](https://uane.edu.mx/) website
- Go to `/nosotros/campus`
- Compare that slider with [UANE](https://uane.edu.mx/nosotros/campus) website
- Keep rocking 🔥 
Note: Content of UANE website can be …
=> [DEV-5251] Migrate slider component

config/vida-estudiantil.json
- Migrate "vida estudiantil" page images from drive to S3
- [feat: vida estudiantil page images migrated](https://github.com/techlottus/portalverse-uane/pull/142/commits/9a753670d3cd01661b134b87bb0e46a292f43031)
- Go to `/nosotros/vida-estudiantil`
- Watch the page and compare with [UANE](https://uane.edu.mx/nosotros/vida-estudiantil)
=> [DEV-5263] Migrate "vida estudiantil" page images

config/footer.json, config/oferta-educativa/bachillerato.json, config/podcast.json, pages/admisiones/becas.tsx, pages/admisiones/pedir-informacion.tsx, pages/contactanos/index.tsx, pages/extension-universitaria/[program]/index.tsx, pages/index.tsx, pages/oferta-educativa/[level]/[program]/index.tsx
- Migrate "bachillerato" and "podcast" pages images from drive to S3
- [feat podcast and bachillerato pages images migrated](https://github.com/techlottus/portalverse-uane/commit/130e5c62dfe32f6eb4327b19ced1b8e339eca769)
- Go to `/oferta-educativa/bachillerato`
- Watch the page and compare with [UANE](https://uane.edu.mx/oferta-educativa/bachillerato) website
- Go to `/voz-uane/podcast`
- Watch the page and compare with [UANE](https://uane.edu.mx/voz-uane/podcast) website
=> [DEV-5265] Migrate "bachillerato" and "podcast" pages images

forms/container/BeWanted.tsx, forms/fixtures/controls.ts, forms/steps/step-one-bewanted.tsx, utils/registerBeWantedAccount.ts
Employability Form's implementation is outdated. Adjustments were made in UTEG's repository and need to be brought back here.
- Checkout to PR.
- Navigate to `/nosotros/bolsa-de-talento` and scroll down to the form.
- Fill in the form. Make sure "Nombre", "Apellidos", "Celular" and "Correo electrónico" fields have no validation errors and validate the following:
- If the password field is left empty, the message "Ingresa una contraseña" is displayed.
- If the given password has a length between 1 and 7 characters, message "Ingresa una contraseña de al menos 8 caracteres" is displayed.
- If the password or any other input has a validation error, the submit button is disabled. Once errors are corrected, the button becomes enabled in order to submit the form.
=> [DEV-5268] Employability Form

config/internacionalizacion.json, old-components/Rainbow.tsx, pages/nosotros/internacionalizacion.tsx
- Migrate Rainbow component from UTEG to that repo
- [feat: Rainboew component migrated](https://github.com/techlottus/portalverse-uane/pull/150/commits/f43c6e47112b5a178e7fcd3f879835f27830cab3)
- Go to `/nosotros/internacionalizacion`
- Watch the "rainbow" images and change size of the browser
- Check that images are not distorted
=> [DEV-5293] Migrate rainbow component

forms/container/BeWanted.tsx, forms/container/EducacionContinuaForm.tsx, forms/container/OpenForm.tsx
Bring latest logic/layout adjustments into `OpenForm`, `EducacionContinuaForm` and `BeWanted` forms from UTEG's repository.
=> [DEV-5297] Forms Adjustments

config/podcast.json, config/voz-UANE.json
we need to update podcast episodes
we update podcast episodes on voz-uane and podcast pages
=> feat: update podcast and voz-uane pages

pages/voz-uane/blog/[entry]/index.tsx, utils/getStrapi.ts
=> Added optional chainings on /voz-uane/blog/[entry]

pages/voz-uane/blog/[entry]/index.tsx
we need to add metadata
we add metadata in blogpost page
=> [DEV-5486] Maintenance p5

config/oferta-educativa/maestria.json, config/oferta-educativa/maestria/gobierno-estrategia.json, routes/Routes.ts
we need to change name an breadcumb label of program gobierno y estrategia publica
we change the name of that program to gobierno y estrategia
=> [DEV-5498] Maintenance sites part 1

config/podcast.json, config/voz-UANE.json, pages/index.tsx, pages/voz-uane/podcast.tsx
=> [Hotfix] Update Data

config/footer.json, old-components/FooterPortalverse.tsx
we need to add new logos certifications
add new logos in footer certifications
=> feat: add new logos certifications

old-components/SliderPortalverse.tsx
Fix `SliderPortalverse` component button alignment
=> Fix: adjust SliderPortalverse Button alignment

pages/_app.tsx
- there were unused gtag codes 
- removed unused code
- CO files
=> chore: removed unused gtags

pages/[...slug].tsx, pages/index.tsx, pages/voz-uane/blog/[entry]/index.tsx, pages/voz-uane/blog/index.tsx
Restore static `/voz-uane/blog` an `/voz-uane/blog/[entry]` pages
=> [DEV-5813] Restore Blog Pages

config/somos-uane.json, old-components/OfertaEducativa.tsx, pages/extension-universitaria/index.tsx
Cards are not redirecting correctly
=> Fix: CardProgram & OfertaEducativa components urls

routes/breadcrumbs.labels.ts
Add `/aviso-de-privacidad-egresados-UANE`page breadcrumb
=> Add "aviso-de-privacidad-egresados-UANE" breadcrumb

routes/breadcrumbs.labels.ts
Adjust `/aviso-privacidad-egresados` url and breadcrumb.
=> Adjust breadcrumb

components/NumbersPortalverseWrapper.tsx, utils/getHomePageData.ts, utils/getPageData.ts, utils/strapi/sections/BlogPostsPodcast.ts, utils/strapi/sections/Listconfig.ts, utils/strapi/sections/OverlayCardList.ts, utils/strapi/sections/StatisticsCardList.ts
Migrate changes from https://github.com/techlottus/portalverse/pull/165
=> [Migration] Update Queries

components/sections/FormVideo.tsx, forms/container/OpenForm.tsx, forms/steps/step-one-openform.tsx, utils/Renderers.tsx, utils/strapi/queries.ts, utils/strapi/sections/FormVideo.ts
Corresponding migration of FormVideo component as implemented in [UTEG project #5845](https://github.com/techlottus/portalverse/pull/169).
=> [DEV-5860] FormVideo component migration

utils/strapi/sections/Listconfig.ts
Migrate changes from UTEG's repository.
=> [DEV-5863] [Migration UTEG - UANE] Listconfig data population validation

components/BlogEntryPageContent.tsx, components/sections/FormVideo.tsx, components/sections/ProgramsFilter.tsx, old-components/Filter/Filter.tsx, package.json, types/Filter.types.ts, types/strapi/common.ts, utils/Renderers.tsx, utils/getPageData.ts, utils/strapi/queries.ts, utils/strapi/sections/ProgramsFilter.tsx
Migrate changes from UTEG's repository.
=> [DEV-5865] [Migration UTEG - UANE] ProgramsFilter renderer

components/sections/ProgramsFilter.tsx, utils/misc.ts, utils/strapi/sections/ProgramsFilter.tsx
Migrate changes from UTEG's repository.
=> [DEV-5866] [Migration UTEG - UANE] Normalize Program Level Route String

components/sections/ContEdPrograms.tsx, old-components/CardProgram/CardProgram.tsx, old-components/Richtext/Richtext.scss, utils/Renderers.tsx, utils/getPageData.ts, utils/strapi/queries.ts, utils/strapi/sections/ContEdPrograms.ts
Migrate changes from UTEG's repository.
=> [DEV-5867] [Migration UTEG - UANE] ContinuousEducationPrograms Section Renderer

pages/index.tsx, utils/getHomePageData.ts, utils/misc.ts, utils/strapi/sections/ProgramsFilter.tsx
=> [DEV-5876] [Migration UTEG - UANE] home page

config/footer.json, old-components/FooterPortalverse.tsx
=> Update footer privacy link

config/becas.json, config/campus.json, config/podcast.json
we need to update podcast
we need to fix texts in becas page
we need to update address campus
podcasts have been updated
texts with misspellings were corrected in becas page
campus addresses updated
=> [DEV-5923] Maintenance sites part1

components/DynamicProgramContent.tsx, components/ProgramSuperiorPageContent.tsx, old-components/OutstandingContainerPortalverse.tsx, old-components/OutstandingModule/OutstandingModule.scss, utils/getProgramBySlug.ts, utils/getProgramDetailSuperior.ts, utils/getProgramsData.ts, utils/pages.ts, utils/programDetail.ts
we need to migrate the component for the top level program detail render
the component has been migrated and added to the component for DynamicProgramContent to be able to render new programs created from strapi UANE
try to generate programs of different higher levels:
- Licenciatura
- Maestria
- Doctorado
-Especialidad
=> [DEV-6000] Superior level detail program UANE

components/DynamicProgramContent.tsx, components/ProgramBachilleratoPageContent.tsx, components/ProgramSuperiorPageContent.tsx, old-components/Richtext/Richtext.tsx, utils/getProgramDetailBachillerato.ts, utils/pages.ts, utils/programDetail.ts
MIGRATION
we need to migrate the educational program detail component of the [https://github.com/techlottus/portalverse/pull/196](url) pr to the UANE repository
the component has been migrated to the UANE repository
=> [DEV-6019] migration bachillerado detail program UANE

config/somos-uane.json
we need to change texts on certifications section from page somos-uane
The paragraph of the somos-uane page in the certifications section has been changed
=> [DEV-6032] Maintenance sites 3

components/sections/ContEdPrograms.tsx, old-components/CardProgram/CardProgram.tsx, types/CardProgram.types.ts, utils/strapi/sections/ContEdPrograms.ts
we need to perform migration of the recategorization of programs from the UTEG repository
the migration of the recategorization of programs from the UTEG repository has been carried out
=> [ENG-635] Migration of recategorization of university extension programs from the UTEG repository to that of UANE

utils/pages.ts, utils/strapi/sections/ProgramsFilter.tsx
=> [ENG-627] Fix: Hide static Licenciatura-level programs

components/BlogEntryPageContent.tsx
We need to migrate changes form pr [204](https://github.com/techlottus/portalverse/pull/204/files) Fix: Add missing onClick prop
the changes of PR [204 ](https://github.com/techlottus/portalverse/pull/204/files)from UTEG to UANE have been migrated
=> [DEV-6045] migration UTEG - UANE Add missing onClick prop

components/sections/FormVideo.tsx, forms/container/OpenForm.tsx, forms/fixtures/controls.ts, forms/fixtures/openform.ts, forms/steps/step-one-openform.tsx, forms/steps/step-three-openform.tsx, forms/steps/step-two-openform.tsx, old-components/OptionPill.tsx, utils/saveDataForms.ts
=> [ENG-677] Formulario de Egresados UANE

forms/fixtures/openform.ts, pages/contactanos/index.tsx
=> Fix: Adjust Open Form copies

README.md
=> [ENG-789] Updated Readme

.gitignore, pages/_app.tsx, pages/_document.tsx, pages/thank-you.tsx
Due to stakeholder's requirement, it's necessary to remove all the references to Pixel implementation within UANE site.
=> [ENG-816] Remove pixel from UANE
