techlottus/portalverse-uane

utils/fetcher.ts, utils/getStrapi.ts
Generate data fetching functions pointing to Strapi's GraphQL API's endpoint.
=> Fetcher GraphQL

config/modelo-educativo.json
- Migrate images of "modelo educativo" page from drive to S3 bucket
- [feat: modelo educativo images migrated](https://github.com/techlottus/portalverse-uane/pull/97/commits/a7b91451657b4a47b06806c551fd52f5cf642bb8)
- Go to `/nosotros/modelo-educativo`
- See and compare images with [UANE](https://uane.edu.mx/nosotros/modelo-educativo) website
=> [DEV-5215] Migrate "modelo educativo" page images

config/empleabilidad.json
- Migrate images of "empleabilidad" page from drive to S3 bucket
- [feat: empleabilidad page images migrated](https://github.com/techlottus/portalverse-uane/pull/99/commits/a69353660a4aea564f6c6208616bc16c9c5b1a25)
- Go to /nosotros/empleabilidad`
- See and compare images with [UANE](https://uane.edu.mx/nosotros/empleabilidad) website
=> [DEV-5218] Migrate "empleabilidad" page images

config/becas.json
- Migrate images of "becas" page from drive to S3 bucket
- [feat: Becas page images migrated](https://github.com/techlottus/portalverse-uane/pull/101/commits/39cbb67f863fd3b1b7176c4a8c2cb64c563060ea)
- Go to `/admisiones/becas`
- See and compare images with [UANE](https://uane.edu.mx/admisiones/becas) website
=> [DEV-5226] Migrate "becas" page images

config/egresados.json
- Migrate images of "egresados page from drive to S3 bucket
- [feat: Egresados page images migrated](https://github.com/techlottus/portalverse-uane/pull/103/commits/a98e1d62dc1719aeaaf1cb09c4b3d9da7a9ce214)
- Go to `/egresados`
- See and compare images with [UANE](https://uane.edu.mx/egresados) website
=> [DEV-5227] Migrate "egresados" page images

config/conexion-educativa.json
- Migrate images of "conexión educativa" page from drive to S3 bucket
- [feat: Conexion educativa page images migrated](https://github.com/techlottus/portalverse-uane/pull/104/commits/72430950de31294e39721c9ca5988b147efbd828)
- Go to `/nosotros/conexion-educativa`
- See and compare images with [UANE](https://uane.edu.mx/nosotros/conexion-educativa) website
=> [DEV-5228] Migrate "conexion educativa" page images

config/alumnos.json
- Migrate images of "alumnos" page from drive to S3 bucket
- [feat: alumnos page images migrated](https://github.com/techlottus/portalverse-uane/pull/105/commits/5c1e0ce8d09bdbf7dcaaa358166194cc2421a698)
- Go to `/alumnos`
- See and compare images with [UANE](https://uane.edu.mx/alumnos) website
=> [DEV-5230] Migrate "alumnos" page images

config/faq.json, config/ponte-en-contacto.json
- Migrate images of "faq" and "contactanos" pages from drive to S3 bucket
- [feat: ponte en contacto page images migrated](https://github.com/techlottus/portalverse-uane/pull/106/commits/9af30c61b01bdc2dc8b3b4e22e898ae9b9af7462)
- [feat: faq page images migrated](https://github.com/techlottus/portalverse-uane/pull/106/commits/ab6e67aba59daf6cb8edd6d618d8870b7af7cb49)
- Go to `/contactanos`
- See and compare images with [UANE](https://uane.edu.mx/contactanos) website
- Go to `/contactanos/faq/general`
- See and compare images with [UANE](https://uane.edu.mx/contactanos/faq/general) website
=> [DEV-5231] Migrate "contactanos" page images

config/egresados-talento.json
- Migrate images of "faq" and "egresados talento" pages from drive to S3 bucket
- [feat: egresados talento page images migrated](https://github.com/techlottus/portalverse-uane/pull/107/commits/baa7420b5077dac04e71e428051acaaac52f6ed0)
- Go to `/egresados/talento`
- See and compare images with [UANE](https://uane.edu.mx/egresados/talento) website
=> [DEV-5233] Migrate "egresados talento" page images

config/oferta-educativa/oferta-educativa.json, routes/Routes.ts
- Migrate images of "oferta educativa" page from drive to S3
- [feat: oferta educativa page images migrated](https://github.com/techlottus/portalverse-uane/commit/1e36d906bb68d6a2cb0ddc2a0993dd733545944d)
- Go to `/oferta-educativa`
- See and compare images with [UANE](https://uane.edu.mx/oferta-educativa) website
=> [DEV-5234] Migrate "oferta educativa" page images

pages/index.tsx, utils/saveDataForms.ts
University Extension Form request to Salesforce is missing `canal` and `source` query params.
- Checkout to PR.
- Run `yarn && yarn dev`.
- Navigate to `/extension-universitaria` and click on any program.
- Fill in the form and check the request in your Developer Tools Network tab.
- Look up the request starting with `formluario_datos_personales`. In the Payload tab, validate that `source` field is sent as `portalUANE` and `canal` as `Página web` (encoded as `P%C3%A1gina%20web`).
=> [Portalverse - UANE] University Extension Form fields

old-components/BannerNumeralia/BannerNumeralia.tsx
- Migrate BannerNumeralia component from UTEG to that repo
- [feat: BannerNumeralia component migrated](https://github.com/techlottus/portalverse-uane/commit/65b56920ac5fc768921ce8d69f5437794703a90d)
- Go to `/egresados`
- Watch the Banner, change the size of the browser and check that the text does not go outside the banner
=> [DEV-5376] Migrate Banner numeralia component

config/alumnos.json, config/podcast.json, config/voz-UANE.json
We need to update podcast in voz-uane and podcast pages
we need to add the card for biblioteca virtual on the page Alumnos
updated podcast and episode in voice uane
The card was added for page n on the page Alumnos
=> feat: update podcast, add card biblioteca virtual in alumnos page

old-components/Editor/Editor.scss
- Make sure of the "b" tag works in the text blog section/page
- [feat: blog styles fixed](https://github.com/techlottus/portalverse-uane/commit/6375b5d9054a672de62b153685e5bf40e3b08a56)
- Go to `/voz-uane/blog/como-utilizar-data-science-para-mejorar-la-experiencia-del-cliente`
- Watch the page and make sure of the "b" tag and the other rich text tags works
=> [DEV-5681] Fix bold text

utils/routes.ts
Items in Strapi's `page` Collection Type without a slug are triggering a build-time error due to a missing optional chaining operator.
=> Fix: add optional chaining on isValidPath

components/sections/PromoLinkList.tsx, old-components/PromoLink.tsx, utils/Renderers.tsx, utils/getPagesData.ts, utils/strapi/queries.ts, utils/strapi/sections/PromoLinkList.ts
Corresponding migration of PromoLinkList component as implemented in [UTEG project #5829](https://github.com/techlottus/portalverse/pull/160).
=> [DEV-5833] PromoLink component migration

components/index.scss, components/sections/CardList/index.tsx, components/sections/CardList/styles.scss, utils/Renderers.tsx, utils/strapi/queries.ts, utils/strapi/sections/CardList.ts
Corresponding migration of PromoLinkList component as implemented in [UTEG project #5830](https://github.com/techlottus/portalverse/pull/170).
=> [DEV-5851] CardList component migration

components/NumbersPortalverseWrapper.tsx, components/sections/StatisticsCardList.tsx, old-components/NumbersPortalverse/NumbersPortalverse.tsx, utils/Renderers.tsx, utils/strapi/queries.ts, utils/strapi/sections/StatisticsCardList.ts
Corresponding migration of StatisticsCardList component as implemented in [UTEG project #5844](https://github.com/techlottus/portalverse/pull/168).
=> [DEV-5859] StatisticsCardList component migration

components/DynamicProgramContent.tsx, pages/[...slug].tsx, utils/getProgramBySlug.ts, utils/pages.ts
Corresponding migration of PromoLinkList component as implemented in [UTEG project #5931](https://github.com/techlottus/portalverse/pull/189).
You can use these already captured programs for the UANE staging environment:
- Bachillerato
- [Strapi Item](https://strapi.staging.uane.edu.mx/admin/content-manager/collectionType/api::program.program/10)
- Program Slug: `/programa-de-prueba-bachillerat`
- Path: `/oferta-educativa/bachillerato/programa-de-prueba-bachillerat`
- [Preview](https://portalverse-uane-git-feat-dev-5997-techlottus.vercel.app/oferta-educativa/bachillerato/programa-de-prueba-bachillerat)
- Licenciatura
- [Strapi Item](https://strapi.staging.uane.edu.mx/admin/content-manager/collectionType/api::program.p …
=> [DEV-5997] Render Level-specific Program Detail Page migration

components/DynamicProgramContent.tsx, components/sections/ContEdProgramDetail.tsx, utils/getProgramBySlug.ts
Corresponding migration of PromoLinkList component as implemented in [UTEG project #5954](https://github.com/techlottus/portalverse/pull/192).
You can use these already captured programs for the UANE staging environment:
- Educación Continua
- [Strapi Item](https://strapi.staging.uteg.edu.mx/admin/content-manager/collectionType/api::program.program/4)
- Program Slug: `/prueba-programa-extension-universitaria`
- Path: `/extension-universitaria/prueba-programa-extension-universitaria`
- [Preview](https://portalverse-uane-git-feat-dev-5999-techlottus.vercel.app/extension-universitaria/prueba-programa-extension-universitaria)
=> [DEV-5999] Continuous education detail page component migration

pages/[...slug].tsx, pages/voz-uane/blog/index.tsx, pages/voz-uane/index.tsx, utils/getBlogPosts.ts, utils/getPodcastEpisodes.ts, utils/strapi/sections/BlogPostsPodcast.ts, utils/strapi/sections/Listconfig.ts
we need to change the pagination variables in the blopost query to get the maxentries, the following pagination has been placed: pagination: `{ start: $start, limit: $limit }` where the value of the start variable is 1 and limit is defined with the maxentries that comes from strapi, when performing tests and placing a -1 we are shown all the available data, the value is not allowed to be null since this is defined from strapi.
we need to change the paging variables in the podcastEpisodes query to get the maxentries, just like blogpost the limit variable will come from strapi's maxentries
=> [DEV-5953] Fix variables pagination UANE

components/sections/ContEdPrograms.tsx, utils/pages.ts, utils/strapi/sections/ContEdPrograms.ts
Corresponding migration of PromoLinkList component as implemented in [UTEG project #5994](https://github.com/techlottus/portalverse/pull/198).
=> [DEV-6027] Refactor Continuous Education programs visibility migration

components/sections/BlogPostsPodcast.tsx, components/sections/PodcastList.tsx, old-components/SliderPortalverse.tsx, utils/pages.ts, utils/strapi/sections/PodcastList.ts
Corresponding migration of PromoLinkList component as implemented in [UTEG project #6022](https://github.com/techlottus/portalverse/pull/202).
- Checkout to PR.
- Run `yarn && yarn dev`
- Navigate to `/cumple-de-beto`.
- The first component is a `HeroSlider` section component with a single side with its `textPosition` set to `right center`. Validate that the button is aligned to the right.
- The third component is a `PodcastList` section component, with its first item being of type `playlist`. Validate that a Spotify playlist is displayed and no errors are shown.
=> [DEV-6042] Fixes/Adjustments (static path generation; PodcastList & Banner components) migration

components/sections/BlogPosts.tsx, pages/nosotros/internacionalizacion.tsx, utils/getBlogPosts.ts, utils/strapi/sections/BlogPosts.ts
We need to migrate the blogpost rendering code by category to implement it in the internationalization page of the UTEG repository
The necessary code for the rendering of the blog notes section related to Internationalization has been migrated
PR migrated:
[https://github.com/techlottus/portalverse/pull/205/files#diff-de28bd6061875ec713a55defd50797c188dddd548076f29e93c9ba57d5382e94](url)
=> [ENG-311] Migración de sección BlogPosts de la página de Internacionalización UANE

components/sections/ContEdProgramDetail.tsx, utils/getProgramBySlug.ts
we need to add the category above the title of each university extension program
The detail model of the university extension program has been modified to add the category on the title of the program
The query has been modified to bring the data of the program category
the typing has been modified to add the property of the category of the program
=> [ENG-807] Add university extension course category on detail page
